### ISSUE TITLE
您号，我按照官方的编译

### ISSUE THREAD

**Issue by trdmm** [TomHeaven/wiznote-release-for-linux#1]
若出现错误：No CMAKE_CXX_COMPILER could be found. mac qt

点击「项目」，打开「构建设置」，在 CMake 构建目录中添加以下两个参数，重新构建即可：
-DCMAKE_C_COMPILER=clang
-DCMAKE_CXX_COMPILER=clang++

下面那两行加在哪啊？

**Comment by TomHeaven** [comment]
为知笔记是基于qt webengine的。Ubuntu 16.04软件源还不支持qt5的webengine，所以你用cmake编译基本没戏。如果想自己编译，下载并且安装qt 5.7，用qt-creator打开cmake文件，创建qt项目再编译即可。
这个问题与项目无关，我close了。
